### ISSUE TITLE
Add configuration option to specify source

### ISSUE THREAD

**Issue by jeffblake** [teespring/nightwing#8]
For example, I prefix all my sources by:

`[environment].[process_type].server.worker`

e.g.

`production.web.1.10`

This way I can have a single Librato account and use it for both staging and production environments.

**Comment by chrisledet** [comment]
You can use the current `:namespace` config key to achieve that:

``` ruby
Sidekiq.configure_server do |config|
  config.server_middleware do |chain|
    chain.add Nightwing::Sidekiq::Stats, client: Librato, namespace: "my_namespace"
  end
end
```

All stats will be prefixed with "my_namespace" or whatever String you provide.

**Comment by jeffblake** [comment]
I want to namespace the `source`, not the `metric`. This lets me use 1 librato account, with the same metrics, and filter using dynamic sources.

**Comment by chrisledet** [comment]
Got cha. Totally makes more sense now. Sorry for the confusion. We'll look into it.

**Comment by jeffblake** [comment]
Thanks, however,

I just found this gem: https://github.com/librato/librato-rack-source_prefix

which takes care of this for us.
